---

- name: Configure the Remmina PPA
  apt_repository: repo="ppa:remmina-ppa-team/remmina-next" state=present

- name: Install Remmina
  apt:
    state: present
    pkg:
      - remmina
      - remmina-plugin-rdp
