---

- name: Add Lyx repository
  apt_repository: repo="ppa:lyx-devel/release" state=present update_cache=yes

- name: Install Lyx
  apt: name=lyx state=latest update_cache=yes cache_valid_time={{ aptcachetime }}