---

- name: Install Nautilus additional packages
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
    pkg:
      - nautilus-compare
      - nautilus-image-converter
      - nautilus-image-manipulator
      - nautilus-wipe

- name: Install Nautilus additional packages for Ubuntu 14.04
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
    pkg:
      - nautilus-open-terminal
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
