---

- name: Install Git
  apt: pkg=git state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  become: true

- name: Setup default git configuraiton
  git_config: name="{{ item.name }}" value="{{ item.value }}" scope=global
  with_items:
    - {name: "user.name",  value: "{{ user_info.name }}" }
    - {name: "user.email", value: "{{ user_info.email  }}" }
