---

- name: Install required packages
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
    pkg:
      - lm-sensors
      - hddtemp

- name: Install Psensor
  apt: pkg=psensor state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
