---

- name: Configure the Claws Mail PPA
  apt_repository: repo="ppa:claws-mail/ppa" state=present

- name: Install Claws Mail
  apt:
    state: latest
    pkg:
      - claws-mail
      - claws-mail-i18n
      - claws-mail-extra-plugins
      - claws-mail-plugins
      - claws-mail-multi-notifier
      - claws-mail-themes
